CREATE TABLE [dbo].[APPPERMISSION] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [APPUSERID]    INT DEFAULT ((0)) NOT NULL,
    [APPSETTINGID] INT DEFAULT ((0)) NOT NULL,
    [PERMISSION]   INT DEFAULT ((0)) NOT NULL,
    [isdeleted]    BIT DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

