CREATE TABLE [dbo].[APPUSER] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [USERNAME]    VARCHAR (200)  DEFAULT ('') NOT NULL,
    [DISPLAYNAME] VARCHAR (200)  DEFAULT ('') NOT NULL,
    [PASSWORD]    NVARCHAR (200) DEFAULT ('') NOT NULL,
    [OTP]         NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [BIRTHDATE]   DATETIME       DEFAULT (getdate()) NOT NULL,
    [ISDELETED]   BIT            DEFAULT ((0)) NOT NULL,
    [PROFILEIMG]  NVARCHAR (MAX)  DEFAULT ('') NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

