CREATE TABLE [dbo].[APPUSERINFO] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [USID]         INT            DEFAULT ((0)) NOT NULL,
    [FIRSTNAME]    VARCHAR (200)  DEFAULT ('') NOT NULL,
    [LASTNAME]     VARCHAR (200)  DEFAULT ('') NOT NULL,
    [GENDER]       BIT            DEFAULT ((1)) NOT NULL,
    [MOBILE]       NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [SOCIAL]       NVARCHAR (100) DEFAULT ('') NOT NULL,
    [BIRTHDATE]    DATETIME       DEFAULT ('1900-01-01') NOT NULL,
    [ADDRESSLINE1] VARCHAR (200)  DEFAULT ('') NOT NULL,
    [ADDRESSLINE2] VARCHAR (200)  DEFAULT ('') NOT NULL,
    [CITY]         NVARCHAR (200) DEFAULT ('') NOT NULL,
    [USTATE]       NVARCHAR (200) DEFAULT ('') NOT NULL,
    [COUNTRYCODE]  NVARCHAR (10)  DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([USID]) REFERENCES [dbo].[APPUSER] ([ID]),
    FOREIGN KEY ([USID]) REFERENCES [dbo].[APPUSER] ([ID])
);

