CREATE TABLE [dbo].[GST] (
    [ID]   INT             IDENTITY (1, 1) NOT NULL,
    [CGST] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [SGST] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [IGST] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

